version: "3.9"

services:
  #Uncommented Postgres info we are implementing mysql as the DB
  #For the time being I also enabled sqlite (django default db)
  # So that a superuser could be created and the admin page accessed.
  #db:
  #  image: postgres
  #  environment: 
  #    - POSTGRES_DB=postgres
  #    - POSTGRES_USER=postgres
  #    - POSTGRES_PASSWORD=postgres
  gudweb:
    build: ./gitgud_web_source/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
   # depends_on: 
   #   - db