version: "3.9"
services:
  #DB goes here
  guddb:
    image: mariadb
    ports: 
      - '3306:3306'
    #command: sh -c "/usr/bin/mysql --user=DBuser --password=SuperSecrets213 --execute \"SHOW DATABASES;\""
    restart: always

    environment:
      MYSQL_DATABASE: 'WebDevDB'
      MYSQL_USER: 'DBuser'
      MYSQL_PASSWORD: 'SuperSecrets213'
      MYSQL_ROOT_PASSWORD: 'YoullNeverGuess'
    #volumes: 
    #  - .DB_Config:/gud_db
  
  gudweb:
    build: ./gitgud_web_source/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/development
    ports:
      - "8000:8000"
    links:
      - guddb
    depends_on:
      - guddb